services:
  rir:
    build: .
    ports:
      - "8010:8010"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: felix
      POSTGRES_PASSWORD: abccba123321
      POSTGRES_DB: rir
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
